package pa2;

import java.awt.Color;
import javax.swing.JColorChooser;


/**
 * The main frame for the drawing application.
 * 
 * @author John C. Bowers <bowersjc@jmu.edu>
 * @version V1, 09/21/16
 */
public class DrawingFrame extends javax.swing.JFrame {

  DrawingPanelController dpController = null;

  /**
   * Creates new form DrawingFrame
   */
  public DrawingFrame() {
    initComponents();
    dpController = new DrawingPanelController((DrawingPanel) drawingPanel);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    toolButtonGroup = new javax.swing.ButtonGroup();
    drawingPanel = new DrawingPanel();
    jToolBar1 = new javax.swing.JToolBar();
    undoButton = new javax.swing.JButton();
    redoButton = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    jLabel1 = new javax.swing.JLabel();
    penToolButton = new javax.swing.JToggleButton();
    segmentToolButton = new javax.swing.JToggleButton();
    rectangleToolButton = new javax.swing.JToggleButton();
    fillToolButton = new javax.swing.JToggleButton();
    jSeparator2 = new javax.swing.JToolBar.Separator();
    selectColorButton = new javax.swing.JButton();
    selectedColorLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    drawingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    javax.swing.GroupLayout drawingPanelLayout = new javax.swing.GroupLayout(drawingPanel);
    drawingPanel.setLayout(drawingPanelLayout);
    drawingPanelLayout.setHorizontalGroup(
        drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
            0, Short.MAX_VALUE));
    drawingPanelLayout.setVerticalGroup(
        drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
            389, Short.MAX_VALUE));

    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);

    undoButton.setText("Undo");
    undoButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        undoButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(undoButton);

    redoButton.setText("Redo");
    redoButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        redoButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(redoButton);
    jToolBar1.add(jSeparator1);

    jLabel1.setText("Tool:");
    jToolBar1.add(jLabel1);

    toolButtonGroup.add(penToolButton);
    penToolButton.setSelected(true);
    penToolButton.setText("Pen");
    penToolButton.setFocusable(false);
    penToolButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    penToolButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    penToolButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        penToolButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(penToolButton);

    toolButtonGroup.add(segmentToolButton);
    segmentToolButton.setText("Segment");
    segmentToolButton.setFocusable(false);
    segmentToolButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    segmentToolButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    segmentToolButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        segmentToolButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(segmentToolButton);

    toolButtonGroup.add(rectangleToolButton);
    rectangleToolButton.setText("Rectangle");
    rectangleToolButton.setFocusable(false);
    rectangleToolButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    rectangleToolButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    rectangleToolButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rectangleToolButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(rectangleToolButton);

    toolButtonGroup.add(fillToolButton);
    fillToolButton.setFocusable(false);
    fillToolButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    fillToolButton.setLabel("Fill");
    fillToolButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    fillToolButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fillToolButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(fillToolButton);
    jToolBar1.add(jSeparator2);

    selectColorButton.setText("Color:");
    selectColorButton.setFocusable(false);
    selectColorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    selectColorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    selectColorButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectColorButtonActionPerformed(evt);
      }
    });
    jToolBar1.add(selectColorButton);

    selectedColorLabel.setBackground(new java.awt.Color(0, 0, 0));
    selectedColorLabel.setText("     ");
    selectedColorLabel
        .setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    selectedColorLabel.setOpaque(true);
    jToolBar1.add(selectedColorLabel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        .addComponent(drawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    layout
        .setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawingPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_undoButtonActionPerformed
    dpController.undo();
  }// GEN-LAST:event_undoButtonActionPerformed

  private void penToolButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_penToolButtonActionPerformed
    dpController.setToolType(DrawingPanelController.DrawingToolType.Pen);
  }// GEN-LAST:event_penToolButtonActionPerformed

  private void segmentToolButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_segmentToolButtonActionPerformed
    dpController.setToolType(DrawingPanelController.DrawingToolType.LineSegment);
  }// GEN-LAST:event_segmentToolButtonActionPerformed

  private void rectangleToolButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rectangleToolButtonActionPerformed
    dpController.setToolType(DrawingPanelController.DrawingToolType.Rectangle);
  }// GEN-LAST:event_rectangleToolButtonActionPerformed

  private void selectColorButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectColorButtonActionPerformed
    Color newColor =
        JColorChooser.showDialog(this, "Select Drawing Color", dpController.getDrawingColor());
    if (newColor != null) {
      dpController.setDrawingColor(newColor);
    }
    selectedColorLabel.setBackground(newColor);
  }// GEN-LAST:event_selectColorButtonActionPerformed

  private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_redoButtonActionPerformed
    dpController.redo();
  }// GEN-LAST:event_redoButtonActionPerformed

  private void fillToolButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fillToolButtonActionPerformed
    dpController.setToolType(DrawingPanelController.DrawingToolType.Fill);
  }// GEN-LAST:event_fillToolButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DrawingFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DrawingFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DrawingFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DrawingFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new DrawingFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel drawingPanel;
  private javax.swing.JToggleButton fillToolButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar.Separator jSeparator2;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JToggleButton penToolButton;
  private javax.swing.JToggleButton rectangleToolButton;
  private javax.swing.JButton redoButton;
  private javax.swing.JToggleButton segmentToolButton;
  private javax.swing.JButton selectColorButton;
  private javax.swing.JLabel selectedColorLabel;
  private javax.swing.ButtonGroup toolButtonGroup;
  private javax.swing.JButton undoButton;
  // End of variables declaration//GEN-END:variables
}
